services:
  # Test Service
  test:
    build:
      context: .
      dockerfile: Dockerfile.test
    volumes:
      - .:/app
      - go-build-cache:/root/.cache/go-build
      - go-mod-cache:/go/pkg/mod
    command: go test -v ./...
  # Test w/ Coverage Service
  test-coverage:
    build:
      context: .
      dockerfile: Dockerfile.test
    volumes:
      - .:/app
      - go-build-cache:/root/.cache/go-build
      - go-mod-cache:/go/pkg/mod
    command: go test -coverprofile=coverage.out -v ./...
  # Test w/ Race Condition Detection
  test-race:
    build:
      context: .
      dockerfile: Dockerfile.test
    volumes:
      - .:/app
      - go-build-cache:/root/.cache/go-build
      - go-mod-cache:/go/pkg/mod
    command: go test -race -v ./...

volumes:
  go-build-cache:
  go-mod-cache: